// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARR12-SNOJBagWaYVxJjy4d9Q4VnjHHkA',
    appId: '1:675734136620:web:8f0f375dadd378eb1eae89',
    messagingSenderId: '675734136620',
    projectId: 'languo-2ce32',
    authDomain: 'languo-2ce32.firebaseapp.com',
    storageBucket: 'languo-2ce32.firebasestorage.app',
    measurementId: 'G-WPEBFXWNR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLKQ9L-Mws0Fa-ZShSJTHqCGjcQSNhIqU',
    appId: '1:675734136620:android:96597392b532eb6f1eae89',
    messagingSenderId: '675734136620',
    projectId: 'languo-2ce32',
    storageBucket: 'languo-2ce32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV2V2Z8bvl3zIwn02pI32oTvoaGsy-ETc',
    appId: '1:675734136620:ios:e31eeceae1c2b3ff1eae89',
    messagingSenderId: '675734136620',
    projectId: 'languo-2ce32',
    storageBucket: 'languo-2ce32.firebasestorage.app',
    iosBundleId: 'com.example.languo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV2V2Z8bvl3zIwn02pI32oTvoaGsy-ETc',
    appId: '1:675734136620:ios:e31eeceae1c2b3ff1eae89',
    messagingSenderId: '675734136620',
    projectId: 'languo-2ce32',
    storageBucket: 'languo-2ce32.firebasestorage.app',
    iosBundleId: 'com.example.languo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARR12-SNOJBagWaYVxJjy4d9Q4VnjHHkA',
    appId: '1:675734136620:web:50a4d397e89ad0c01eae89',
    messagingSenderId: '675734136620',
    projectId: 'languo-2ce32',
    authDomain: 'languo-2ce32.firebaseapp.com',
    storageBucket: 'languo-2ce32.firebasestorage.app',
    measurementId: 'G-N3XRENBXN1',
  );
}
